"""Cross-model color calibration for frame continuity.

When scene B depends on scene A and they were generated by different backends
(e.g. Kling -> CogVideoX), their color grading can differ significantly.
This module calibrates B's first frame to match the color profile of A's last
frame using histogram matching, then uses the calibrated frame as the i2v
starting image for scene B.

Falls back gracefully if opencv or numpy are unavailable.
"""
from __future__ import annotations

import os
import shutil
from typing import TYPE_CHECKING


class ColorCalibrator:
    """Histogram-based cross-model color calibration.

    Usage:
        calibrator = ColorCalibrator()
        calibrated_path = calibrator.calibrate(source_frame, target_frame, output_path)
        # calibrated_path is a new image that has target_frame's content
        # but source_frame's color distribution — use as i2v input.
    """

    def __init__(self, method: str = "histogram"):
        """
        Parameters
        ----------
        method:
            'histogram' — channel-wise histogram matching (default, fast)
            'mean_std'  — simpler mean/std transfer (fallback)
        """
        self.method = method
        self._cv2_available = self._check_cv2()

    @staticmethod
    def _check_cv2() -> bool:
        try:
            import cv2  # noqa: F401
            import numpy  # noqa: F401
            return True
        except ImportError:
            return False

    def calibrate(
        self,
        reference_path: str,   # last frame of predecessor scene (color source)
        target_path: str,      # first frame of successor scene (to be calibrated)
        output_path: str,      # where to save the calibrated frame
    ) -> str:
        """Calibrate target_path to match reference_path color profile.

        Returns output_path on success, target_path unchanged on failure.
        """
        if not self._cv2_available:
            return self._fallback(reference_path, target_path, output_path)
        if not os.path.exists(reference_path) or not os.path.exists(target_path):
            return target_path
        try:
            if self.method == "histogram":
                return self._histogram_match(reference_path, target_path, output_path)
            return self._mean_std_transfer(reference_path, target_path, output_path)
        except Exception:
            return self._fallback(reference_path, target_path, output_path)

    def _histogram_match(self, ref_path: str, tgt_path: str, out_path: str) -> str:
        import cv2
        import numpy as np

        ref = cv2.imread(ref_path)
        tgt = cv2.imread(tgt_path)
        if ref is None or tgt is None:
            return tgt_path

        # Resize ref to match tgt dimensions if needed (only for histogram source)
        ref_resized = cv2.resize(ref, (tgt.shape[1], tgt.shape[0]))

        result = np.zeros_like(tgt)
        for c in range(3):  # B, G, R channels
            result[:, :, c] = self._match_channel(
                tgt[:, :, c], ref_resized[:, :, c]
            )

        os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
        cv2.imwrite(out_path, result)
        return out_path

    @staticmethod
    def _match_channel(source: "np.ndarray", reference: "np.ndarray") -> "np.ndarray":
        """Match source channel histogram to reference channel."""
        import numpy as np

        src_flat = source.flatten().astype(np.float32)
        ref_flat = reference.flatten().astype(np.float32)

        src_hist, _ = np.histogram(src_flat, bins=256, range=(0, 256))
        ref_hist, _ = np.histogram(ref_flat, bins=256, range=(0, 256))

        src_cdf = np.cumsum(src_hist).astype(np.float32)
        src_cdf /= src_cdf[-1]
        ref_cdf = np.cumsum(ref_hist).astype(np.float32)
        ref_cdf /= ref_cdf[-1]

        # Build lookup table
        lut = np.zeros(256, dtype=np.uint8)
        j = 0
        for i in range(256):
            while j < 255 and ref_cdf[j] < src_cdf[i]:
                j += 1
            lut[i] = j

        return lut[source]

    def _mean_std_transfer(self, ref_path: str, tgt_path: str, out_path: str) -> str:
        """Simpler Reinhard-style mean/std color transfer in LAB space."""
        import cv2
        import numpy as np

        ref = cv2.imread(ref_path).astype(np.float32)
        tgt = cv2.imread(tgt_path).astype(np.float32)
        if ref is None or tgt is None:
            return tgt_path

        ref_lab = cv2.cvtColor(ref, cv2.COLOR_BGR2LAB)
        tgt_lab = cv2.cvtColor(tgt, cv2.COLOR_BGR2LAB)

        for c in range(3):
            ref_mean, ref_std = ref_lab[:, :, c].mean(), ref_lab[:, :, c].std() + 1e-6
            tgt_mean, tgt_std = tgt_lab[:, :, c].mean(), tgt_lab[:, :, c].std() + 1e-6
            tgt_lab[:, :, c] = (tgt_lab[:, :, c] - tgt_mean) * (ref_std / tgt_std) + ref_mean

        tgt_lab = np.clip(tgt_lab, 0, 255)
        result = cv2.cvtColor(tgt_lab.astype(np.uint8), cv2.COLOR_LAB2BGR)
        os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
        cv2.imwrite(out_path, result)
        return out_path

    @staticmethod
    def _fallback(ref_path: str, tgt_path: str, out_path: str) -> str:
        """No cv2 available — copy target unchanged."""
        os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
        shutil.copy2(tgt_path, out_path)
        return out_path


def extract_first_frame(video_path: str, output_dir: str | None = None) -> str | None:
    """Extract the first frame of a video as JPEG. Returns path or None."""
    if not video_path or not os.path.exists(video_path):
        return None
    try:
        from moviepy.editor import VideoFileClip
        from PIL import Image
        clip = VideoFileClip(video_path)
        frame = clip.get_frame(0.0)
        clip.close()
        out_dir = output_dir or os.path.dirname(video_path)
        out = os.path.join(out_dir, os.path.basename(video_path).replace(".mp4", "_first_frame.jpg"))
        Image.fromarray(frame).save(out, format="JPEG", quality=92)
        return out
    except Exception:
        return None
